### ISSUE TITLE
Missing bower.json

### ISSUE THREAD

**Issue by roelio** [stamkracht/donatello#1]
The repo seems to be missing the bower.json file which causes the gulp bower job to fail.

`[11:52:14] Using gulpfile ~/work/stamkracht/donatello/gulpfile.js
[11:52:14] Starting 'bower'...
[11:52:14] 'bower' errored after 3.19 ms
[11:52:14] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/roel/work/stamkracht/donatello/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/roel/work/stamkracht/donatello/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/roel/work/stamkracht/donatello/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/roel/work/stamkracht/donatello/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/home/roel/work/stamkracht/donatello/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/home/roel/work/stamkracht/donatello/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/home/roel/work/stamkracht/donatello/gulp_tasks/task.bower.js:13:10)
    at module.exports (/home/roel/work/stamkracht/donatello/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/roel/work/stamkracht/donatello/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/roel/work/stamkracht/donatello/node_modules/orchestrator/index.js:214:10)
`

**Comment by JordyPouw** [comment]
@roelio Updated the gulp task (bower.js). It will only init if there is a bower.json in the project dir. If there is no bower used, it just skips the task with a feedback message in the terminal that it is not used.
